# Generated by Django 4.0.6 on 2022-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('sexo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('quarteirao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quarteirão')),
                ('numero_de_casa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nr Casa')),
                ('bilhete_de_identidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='BI')),
                ('estado', models.CharField(blank=True, default='Inativo', max_length=100, null=True, verbose_name='Estado do Voto')),
            ],
        ),
    ]
