# Generated by Django 4.0.6 on 2022-07-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleitor',
            name='estado',
            field=models.CharField(choices=[('Inativo', 'Inativo'), ('Ativo', 'Ativo')], default='Inativo', max_length=100, verbose_name='Estado do Voto'),
        ),
    ]
